Raw_Table_Staging_Configurations:
  DuckDB_File: "galvanic.duckdb"
  Data_Staging:
    Session_Metadata:
      Source_File: "source/session_metadata.csv"
      Staging_Table: "staging.session_metadata"
      Schema_Name: "SessionMetadata"
      Full_Load: False
    Timeline_Metadata:
      Source_File: "source/timeline_metadata.csv"
      Staging_Table: "staging.timeline_metadata"
      Schema_Name: "TimelineMetadata"
      Full_Load: False
    Timeline_Metadata_11272025:
      Source_File: "source/timeline_metadata_11272025.csv"
      Staging_Table: "staging.timeline_metadata_11272025"
      Schema_Name: "TimelineMetadata11272025"
      Full_Load: False
    Ads_Metadata:
      Source_File: "source/ads_metadata.csv"
      Staging_Table: "staging.ads_metadata"
      Schema_Name: "AdsMetadata"
      Full_Load: False
    Ads_Metadata_11272025:
      Source_File: "source/ads_metadata_v2.csv"
      Staging_Table: "staging.ads_metadata_11272025"
      Schema_Name: "AdsMetadata11272025"
      Full_Load: False
    LIWC_Metadata:
      Source_File: "source/2-final_LIWC_merged_with_ads_and_sessionmeta__with_MediaScope.csv"
      Staging_Table: "staging.liwc_metadata"
      Full_Load: True

Text_Preprocessing_Configurations:
  DuckDB_File: "galvanic.duckdb"
  Transcript_Source_Table: "staging.liwc_metadata"
  Ollama_Endpoint: "http://localhost:11434/v1"
  Emotion_Classifier_Model:
    Model_Name: "SamLowe/roberta-base-go_emotions"
    Model_Source: "Hugging Face"
    Output_Table: "staging.emotion_predictions"
  Ads_Categorization_Model:
    Ollama_Parameters:
      model: "gpt-oss:120b"
      max_tokens: 32768
      temperature: 1.0
      top_p: 1.0
    Output_Table: "staging.ads_predictions"